# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cucumber_growlnotify}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rodrigo Oliveira"]
  s.date = %q{2011-03-09}
  s.description = %q{This gem notifies through growl that your cucumber tests are passing or not}
  s.email = %q{rodrigo.dealer@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "cucumber_growlnotify.gemspec",
    "lib/cucumber_growlnotify.rb",
    "resources/fail.png",
    "resources/success.png",
    "test/helper.rb",
    "test/test_cucumber_growlnotify.rb"
  ]
  s.homepage = %q{http://github.com/rodrigodealer/cucumber_growlnotify}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{This gem notifies through growl that your cucumber tests are passing or not}
  s.test_files = [
    "test/helper.rb",
    "test/test_cucumber_growlnotify.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_runtime_dependency(%q<cucumber>, ["= 0.10.0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<cucumber>, ["= 0.10.0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<cucumber>, ["= 0.10.0"])
  end
end

